package io.dimasla4ee.shoppinglist.core.domain.model

enum class ShoppingListIcon {
    LIST_ALT,
    LIST_ALT_ADD,
    SHOPPING_BAG,
    SHOPPING_CART,
    CAKE,
    CELEBRATION,
    DRINKS,
    PICNIC_TABLE,
    PRESENT,
    BABY_STROLLER,  // TODO: В файле опечатка (stoller)
    BONE,
    CAT,
    CHILD,
    INFANT,
    PAW,
    CONSTRUCTION,
    HOME,
    MICROWAVE,
    DUMBBELL,       // TODO: TODO: В файле опечатка (dumbell)
    FLOWER,
    GAMEPAD,
    JIGSAW,
    MEDICATION,
    MEDITATION,
    PALETTE,
    PHOTO_CAMERA,
    SELF_CARE,
    SKATEBOARD,
    SNOWBOARD,
    WALK,
    CREDIT_CARD,
    LUGGAGE,
    SHIRT,
    WALLET,
    CAR,
    DEVICES,
    DOCS_ADD,
    GRADUATE,
    IMPORT_CONTACTS,
    LIBRARY_ADD_CHECK,
    ADD_CIRCLE,
    CANCEL_CIRCLE,
    CLEAR,
    COPY,
    DELETE,
    DRAG_HANDLE,
    DRAG_PAN,
    EDIT,
    LOGOUT,
    REMOVE_CIRCLE,
    SORT_BY_ALPHA,
    SWAP_VERT
}